### ISSUE TITLE
requestId: 'Unknown Request ID' when calling Manga.getMultiple

### ISSUE THREAD

**Issue by jNullj** [md-y/mangadex-full-api#69] opened 2022-12-17 20:13 UTC
```
APIRequestError: HTTPS GET Response (/manga?contentRating%5B%5D=safe&contentRating%5B%5D=suggestive&contentRating%5B%5D=erotica&contentRating%5B%5D=pornographic&limit=100&ids%5B%5D=175f2083-f5d0-4fe4-9f02-902024675722&ids%5B%5D=432efa9a-f0e4-4b12-b69c-9085d9df5978&ids%5B%5D=e888094f-f564-4d7c-8a4f-1e58729911df&ids%5B%5D=b4400753-0504-4f3b-97e3-f4883c8c027c&ids%5B%5D=142c8b44-678f-4e0d-8005-e5d97094e04c&ids%5B%5D=10ab7de4-c6ed-474c-b669-49a71d271294&ids%5B%5D=72c4a9d3-012c-4f00-a810-1e9a9ef84850&ids%5B%5D=85fc32e3-708c-43ba-9a26-e879a8f574e8&ids%5B%5D=33fcf28c-9282-43ed-b01d-17113fbbb092&ids%5B%5D=129d2724-2604-4b60-a762-eea533cd110c&ids%5B%5D=4175d425-f81f-44a3-b107-aa4a78e8896d&ids%5B%5D=6ed55dc4-7654-48a2-886e-7d70e56e83f0&ids%5B%5D=f74bda04-6923-4c35-a2b7-eea5a7f8cb4a&ids%5B%5D=5ad5d6fc-2736-443f-94a4-0f2407108ce7&ids%5B%5D=40f36d48-0dfd-41e0-96c4-70000a7e5512&ids%5B%5D=7b9d73ff-a19e-4817-9eb7-657471f4d8d5&ids%5B%5D=416b4d65-e0cc-4f6f-bd15-9c0d54e61845&ids%5B%5D=c2e48dab-d156-4ed1-b758-6ea67a6d8910&ids%5B%5D=7b477783-9960-40c8-bd2e-304e6868e7bc&ids%5B%5D=05be3fec-cdec-47df-b9c2-ebc6bbf7407d&ids%5B%5D=3791477a-a18c-48a7-bccd-2dadd8337832&ids%5B%5D=958ea02d-bda3-457e-a45b-e0cc3dd161ff&ids%5B%5D=fbf95c63-dc64-4518-9ed8-362805165fd6&ids%5B%5D=8265ac42-6962-416c-bcb9-cc30915d5856&ids%5B%5D=f9972c2d-b8e0-45e6-a069-8410614e03e7&ids%5B%5D=25d6f2b5-bc22-47ae-9c37-2e4bba9edd6c&ids%5B%5D=826fce22-a1aa-45e7-949b-cd812360304a&ids%5B%5D=c3e2adca-1053-4295-8d4c-feea5f02745c&ids%5B%5D=7e538d58-7927-41fa-af10-9b13a743977b&ids%5B%5D=6a335556-120f-4705-bea4-0bc3d2e1d2b6&ids%5B%5D=962e1500-59e3-47a7-a7f8-21708f7fa044&ids%5B%5D=af857779-a400-46ef-917a-3b3a248e2221&ids%5B%5D=476474de-b227-4c32-91d3-02c330bdb15e&ids%5B%5D=a7e361c2-6777-4cba-bc0f-4e296d36df3d&ids%5B%5D=a6d25ed2-1d11-4fbb-b5ec-3310a087570d&ids%5B%5D=fc365b61-0551-4973-be73-19a4ac4a1c4e&ids%5B%5D=d3f961f6-8ed7-4801-a4cb-79f42890b305&ids%5B%5D=71f90174-12c4-4e5c-bea4-5adbfb086de4&ids%5B%5D=8ff51321-6f0e-4b98-8a9d-be6d8d8f1aa9&ids%5B%5D=15db1e46-ef82-47e0-82d8-360753dfc95d&ids%5B%5D=9bafccba-0cb1-4f4c-a0fc-0dcffb7cdab0&ids%5B%5D=9b8aa3c5-a968-4258-8b5b-4c19e8c54812&ids%5B%5D=78245f07-8313-4245-81d6-5e7a7f05eb85&ids%5B%5D=288a9b95-fead-43e2-99e8-ac0e85802e59&ids%5B%5D=d54b5ba8-17c9-4774-8fb9-98593ebdf8e8&ids%5B%5D=d5166c97-9cf1-4a0a-b8ec-c9577752687e&ids%5B%5D=94329639-1470-4f43-87fb-d61022c5fe96&ids%5B%5D=a41e5721-d0dc-4c5a-b995-b899956f1aa8&ids%5B%5D=63378c84-b7c8-48a5-81d0-41ca66119962&ids%5B%5D=9ff36bf4-03e2-4b30-937c-71a195e3aca1&ids%5B%5D=99fff829-d4f3-4239-9cc4-4c1cfadb45a0&ids%5B%5D=9cc352f9-0708-4726-b570-a3e0312d90ea&ids%5B%5D=d50c445c-96aa-4ff3-8634-1f066c038168&ids%5B%5D=515effc1-cbd2-4e21-80e7-488ef149bf5d&ids%5B%5D=ab648ff6-ccc3-4662-b9fd-1d4624f015fd&ids%5B%5D=a4f4128c-655a-49fb-8181-e5930bedfb4a&ids%5B%5D=eb9385a1-c240-4770-9ba9-e35a987a3a20&ids%5B%5D=b5a53d6b-c0f0-40b7-b5a6-f61a1ad2c5cb&ids%5B%5D=0b85ac0f-6799-4647-8e90-97ca22614b28&ids%5B%5D=319ac4d3-d9f7-4d2c-9b11-f7ff7091300d&ids%5B%5D=f1d0b1df-5fc6-4b01-b69b-ae78eecb1d6d&ids%5B%5D=79a7f762-ca32-416a-a80d-e585138e8ed2&ids%5B%5D=56b91571-9a6f-429d-9a0d-f421eeed4c4d&ids%5B%5D=3ff5e5b9-cc54-49c5-a601-c5d74ed7e023&ids%5B%5D=9dda271c-2998-4659-975b-f0a05247db1a&ids%5B%5D=51e1b2f2-8e20-4ece-a271-81959e37e22d&ids%5B%5D=decf241e-74c8-43fd-aed9-af47aeb4c5b7&ids%5B%5D=8bebe4dc-9fff-4134-aaa6-34736b4b696b&ids%5B%5D=340273ab-6f5a-4eb8-abdf-269343213e4e&ids%5B%5D=fd824304-2f3f-44bc-a8ae-996f6ed1cacb&ids%5B%5D=a85c98a0-291d-44b0-87df-c7ab10b7d853&ids%5B%5D=9002b2bd-feac-44b2-b118-ddac0e7dcaad&ids%5B%5D=5c5ccf39-6e2e-462e-870c-5ad32a98cf99&ids%5B%5D=08a8e772-e878-40e8-951a-c49d99ee6291&ids%5B%5D=7551c6c8-1b5b-4e90-9f25-ed585946438a&ids%5B%5D=1e9f69ab-2107-44c2-a84c-78f3911cdea5&ids%5B%5D=adebd31b-c8c4-4b46-b2b2-7e3f3a234eb2&ids%5B%5D=29de68c5-756a-4429-9005-6b10225bf58a&ids%5B%5D=6cfc369f-2a91-4321-998f-ab344a95c2b4&ids%5B%5D=ef1d242f-964f-429e-9ddc-9f0f485f8ab9&ids%5B%5D=22a86d7c-6827-402c-80af-dbdee3c6c6aa&ids%5B%5D=7ae3cc8e-cc2a-450e-a778-a769f8ee66bf&ids%5B%5D=7f797a03-f5ee-4f2f-be93-b2248d5082e0&ids%5B%5D=97b20185-5481-40c7-86b3-6d5a7e315d7f&ids%5B%5D=2ac32dff-fc19-4f1d-a737-e505d48e3753&ids%5B%5D=c8aebcc7-678e-4682-a727-48febbc325fd&ids%5B%5D=559ad140-e7ce-48ce-af84-b2808268f151&ids%5B%5D=e8b91f74-a71d-427c-b869-018fba8384c1&ids%5B%5D=75e39e98-e523-485b-8037-78cc006f340c&ids%5B%5D=f99a0315-e833-445b-874e-eb0b5de64354&ids%5B%5D=d51470e2-3c32-4516-b614-5ce763ae57a1&ids%5B%5D=ccb03ab9-94e3-4a81-8bb8-44398edf51e0&ids%5B%5D=5786f87f-f98d-4773-8556-066e637f3c50&ids%5B%5D=e0fd795a-f6f3-4a88-ac60-4219a8f1702d&ids%5B%5D=35b35c45-dde0-4805-995f-db862dc2810a&ids%5B%5D=c638dabe-d173-43ff-aba3-d35db5f37dfe&ids%5B%5D=da7c2f82-68af-432f-8a57-2b2271ed1db4&ids%5B%5D=cfdc5375-facb-477a-a229-d75a7d326064&ids%5B%5D=300bf25a-8bfd-4f9f-82df-188113e1d691&ids%5B%5D=a5a4da33-4f3c-4035-ae11-51ee8ba2c263) 
returned an error:
Error: aborted
    at IncomingMessage.<anonymous> (removed_path\node_modules\mangadex-full-api\src\util.js:103:24)
    at IncomingMessage.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 0,
  requestId: 'Unknown Request ID'
}
```

getting this after that:
```js
            function temp(){
                console.log('done with chapters')
                var manga_id_arr = [];
                my_chapters.forEach(val => {
                    let myid = val.manga.id;
                    manga_id_arr.push(myid);
                })
                return manga_id_arr.filter(onlyUnique);
            }
            var uniqeu_manga_id_arr = await temp();
let newManga = await MFA.Manga.getMultiple(uniqeu_manga_id_arr);
```

anything i did wrong? i think this started happening after upgrading to the latest version

tried to revert to 5.11.1, still having the issue, im confused of what could have caused this... how can i get you more usefull info?
update: after updating node.js from 16.15.0 to 18.12.1 version 5.11.1 started working again, 5.12.1 still does not work
update: it happends randomly, regardless of the version... was able to get it to work one time with 5.12.1, no idea why it does not work most of the time

**Comment by md-y** [comment] 2022-12-18 23:15
I was unable to replicate the error. Can I have more information about the request body, like what is the list of manga ids being requested?

This is the list I tested with, which I got from the error URL:
<details>
<summary>List of IDs</summary>

```
175f2083-f5d0-4fe4-9f02-902024675722
432efa9a-f0e4-4b12-b69c-9085d9df5978
e888094f-f564-4d7c-8a4f-1e58729911df
b4400753-0504-4f3b-97e3-f4883c8c027c
142c8b44-678f-4e0d-8005-e5d97094e04c
10ab7de4-c6ed-474c-b669-49a71d271294
72c4a9d3-012c-4f00-a810-1e9a9ef84850
85fc32e3-708c-43ba-9a26-e879a8f574e8
33fcf28c-9282-43ed-b01d-17113fbbb092
129d2724-2604-4b60-a762-eea533cd110c
4175d425-f81f-44a3-b107-aa4a78e8896d
6ed55dc4-7654-48a2-886e-7d70e56e83f0
f74bda04-6923-4c35-a2b7-eea5a7f8cb4a
5ad5d6fc-2736-443f-94a4-0f2407108ce7
40f36d48-0dfd-41e0-96c4-70000a7e5512
7b9d73ff-a19e-4817-9eb7-657471f4d8d5
416b4d65-e0cc-4f6f-bd15-9c0d54e61845
c2e48dab-d156-4ed1-b758-6ea67a6d8910
7b477783-9960-40c8-bd2e-304e6868e7bc
05be3fec-cdec-47df-b9c2-ebc6bbf7407d
3791477a-a18c-48a7-bccd-2dadd8337832
958ea02d-bda3-457e-a45b-e0cc3dd161ff
fbf95c63-dc64-4518-9ed8-362805165fd6
8265ac42-6962-416c-bcb9-cc30915d5856
f9972c2d-b8e0-45e6-a069-8410614e03e7
25d6f2b5-bc22-47ae-9c37-2e4bba9edd6c
826fce22-a1aa-45e7-949b-cd812360304a
c3e2adca-1053-4295-8d4c-feea5f02745c
7e538d58-7927-41fa-af10-9b13a743977b
6a335556-120f-4705-bea4-0bc3d2e1d2b6
962e1500-59e3-47a7-a7f8-21708f7fa044
af857779-a400-46ef-917a-3b3a248e2221
476474de-b227-4c32-91d3-02c330bdb15e
a7e361c2-6777-4cba-bc0f-4e296d36df3d
a6d25ed2-1d11-4fbb-b5ec-3310a087570d
fc365b61-0551-4973-be73-19a4ac4a1c4e
d3f961f6-8ed7-4801-a4cb-79f42890b305
71f90174-12c4-4e5c-bea4-5adbfb086de4
8ff51321-6f0e-4b98-8a9d-be6d8d8f1aa9
15db1e46-ef82-47e0-82d8-360753dfc95d
9bafccba-0cb1-4f4c-a0fc-0dcffb7cdab0
9b8aa3c5-a968-4258-8b5b-4c19e8c54812
78245f07-8313-4245-81d6-5e7a7f05eb85
288a9b95-fead-43e2-99e8-ac0e85802e59
d54b5ba8-17c9-4774-8fb9-98593ebdf8e8
d5166c97-9cf1-4a0a-b8ec-c9577752687e
94329639-1470-4f43-87fb-d61022c5fe96
a41e5721-d0dc-4c5a-b995-b899956f1aa8
63378c84-b7c8-48a5-81d0-41ca66119962
9ff36bf4-03e2-4b30-937c-71a195e3aca1
99fff829-d4f3-4239-9cc4-4c1cfadb45a0
9cc352f9-0708-4726-b570-a3e0312d90ea
d50c445c-96aa-4ff3-8634-1f066c038168
515effc1-cbd2-4e21-80e7-488ef149bf5d
ab648ff6-ccc3-4662-b9fd-1d4624f015fd
a4f4128c-655a-49fb-8181-e5930bedfb4a
eb9385a1-c240-4770-9ba9-e35a987a3a20
b5a53d6b-c0f0-40b7-b5a6-f61a1ad2c5cb
0b85ac0f-6799-4647-8e90-97ca22614b28
319ac4d3-d9f7-4d2c-9b11-f7ff7091300d
f1d0b1df-5fc6-4b01-b69b-ae78eecb1d6d
79a7f762-ca32-416a-a80d-e585138e8ed2
56b91571-9a6f-429d-9a0d-f421eeed4c4d
3ff5e5b9-cc54-49c5-a601-c5d74ed7e023
9dda271c-2998-4659-975b-f0a05247db1a
51e1b2f2-8e20-4ece-a271-81959e37e22d
decf241e-74c8-43fd-aed9-af47aeb4c5b7
8bebe4dc-9fff-4134-aaa6-34736b4b696b
340273ab-6f5a-4eb8-abdf-269343213e4e
fd824304-2f3f-44bc-a8ae-996f6ed1cacb
a85c98a0-291d-44b0-87df-c7ab10b7d853
9002b2bd-feac-44b2-b118-ddac0e7dcaad
5c5ccf39-6e2e-462e-870c-5ad32a98cf99
08a8e772-e878-40e8-951a-c49d99ee6291
7551c6c8-1b5b-4e90-9f25-ed585946438a
1e9f69ab-2107-44c2-a84c-78f3911cdea5
adebd31b-c8c4-4b46-b2b2-7e3f3a234eb2
29de68c5-756a-4429-9005-6b10225bf58a
6cfc369f-2a91-4321-998f-ab344a95c2b4
ef1d242f-964f-429e-9ddc-9f0f485f8ab9
22a86d7c-6827-402c-80af-dbdee3c6c6aa
7ae3cc8e-cc2a-450e-a778-a769f8ee66bf
7f797a03-f5ee-4f2f-be93-b2248d5082e0
97b20185-5481-40c7-86b3-6d5a7e315d7f
2ac32dff-fc19-4f1d-a737-e505d48e3753
c8aebcc7-678e-4682-a727-48febbc325fd
559ad140-e7ce-48ce-af84-b2808268f151
e8b91f74-a71d-427c-b869-018fba8384c1
75e39e98-e523-485b-8037-78cc006f340c
f99a0315-e833-445b-874e-eb0b5de64354
d51470e2-3c32-4516-b614-5ce763ae57a1
ccb03ab9-94e3-4a81-8bb8-44398edf51e0
5786f87f-f98d-4773-8556-066e637f3c50
e0fd795a-f6f3-4a88-ac60-4219a8f1702d
35b35c45-dde0-4805-995f-db862dc2810a
c638dabe-d173-43ff-aba3-d35db5f37dfe
da7c2f82-68af-432f-8a57-2b2271ed1db4
cfdc5375-facb-477a-a229-d75a7d326064
300bf25a-8bfd-4f9f-82df-188113e1d691
a5a4da33-4f3c-4035-ae11-51ee8ba2c263
```
</details>

The error is originating from Node's request library after receiving the raw response from MangaDex, so it might be a problem on MangaDex's side or with Node.

**Comment by md-y** [comment] 2022-12-19 19:15
I wasn't able to replicate the issue with the manga list you provided or by using the RSS script with my own MangaDex account. I tested it on Node version 18.12.1 and MFA version 5.12.1.

I will close this issue with the assumption that the issue is on MangaDex's end.

**Closed by md-y** 2022-12-19 19:15 UTC
